#!/bin/bash

set -e

NR_DOCS_VENV_PATH=/home/ron/prace/nr-docs/.venv/bin/activate
SCRIPT_PATH=$(realpath "$0")
SCRIPT_DIR=$(dirname "$SCRIPT_PATH")

TOKEN_FILE1="current_token_user1.txt"
TOKEN_FILE2="current_token_user2.txt"

. $NR_DOCS_VENV_PATH
cd $SCRIPT_DIR

if [ ! -f "$TOKEN_FILE1" ]; then
    invenio users create --password segrdrgh -a -c ron2@ron.ron
    TOKEN1=$(invenio tokens create -n rtoken -u ron2@ron.ron)
    echo "$TOKEN1" > "$TOKEN_FILE1"
else
    TOKEN1=$(<"$TOKEN_FILE1")
fi
if [ ! -f "$TOKEN_FILE2" ]; then
    invenio users create --password segrdrgh -a -c sylvi2@sylvi.sylvi
    TOKEN2=$(invenio tokens create -n stoken -u sylvi2@sylvi.sylvi)
    echo "$TOKEN2" > "$TOKEN_FILE2"
else
    TOKEN2=$(<"$TOKEN_FILE2")
fi
cat "$TOKEN_FILE1"
cat "$TOKEN_FILE2"

pip install -e .
python ./nrdocs/entry_script.py $TOKEN1 $TOKEN2 $@
