#!/bin/bash
set -e
NR_DOCS_VENV_PATH=/home/ron/prace/nr-docs/.venv/bin/activate
SCRIPT_PATH=$(realpath "$0")
SCRIPT_DIR=$(dirname "$SCRIPT_PATH")

invenio oarepo cf init
invenio communities custom-fields init
invenio oarepo fixtures load