#!/bin/bash
set -e

SCRIPT_PATH=$(realpath "$0")
SCRIPT_DIR=$(dirname "$SCRIPT_PATH")
cd "$SCRIPT_DIR"

VENV_PATH=$(get_nr_docs_dir "$@")
. $VENV_PATH

for file in "$(pwd)"/current_token_*; do
  if [ -e "$file" ]; then
    echo "Deleting: $file"
    rm $file
  fi
done

invenio db drop --yes-i-know
invenio db create
invenio index destroy --yes-i-know
invenio index init
invenio oarepo cf init
invenio communities custom-fields init
invenio files location default s3://default --default
invenio oarepo fixtures load --batch-size 1000 --verbose

invenio oarepo fixtures load --no-system-fixtures /home/ron/prace/nr-docs/fixtures --batch-size 1000 --verbose
