#!/bin/bash
set -e
if [ -f "token.txt" ]; then
    echo "token deleted"
    rm -f token.txt
fi
invenio db drop
invenio db create
invenio index destroy --yes-i-know
invenio index init
invenio oarepo cf init
invenio communities custom-fields init
invenio files location default s3://nrdocs --default
invenio oarepo fixtures load
