#!/bin/bash
if [ $# -eq 0 ]; then
    ENV_NAME=".venv-builder"
elif [ "$1" == "builder" ]; then
    ENV_NAME=".venv-builder"
elif [ "$1" == "tests" ]; then
    ENV_NAME=".venv-tests"
else
    ENV_NAME="$1"
fi
rm -rf "$ENV_NAME"
python3 -m venv "$ENV_NAME"
. "$ENV_NAME/bin/activate"
pip install -U setuptools pip wheel
pip install /home/ron/prace/global_scripts

