#!/bin/bash
export OAREPO_VERSION=12

files_to_run=("run_tests.sh" "run-tests.sh")

for file in "${files_to_run[@]}"; do
    if [ -e "$file" ]; then
        echo "File $file exists. Running it..."
        # Add any additional commands you want to run before executing the file
        bash "$file"
        break  # Exit the loop after running the first existing file
    else
        echo "File $file does not exist."
    fi
done
